Pass all MON addresses in relation databag.
canonical/charm-microceph pull request #97
Opened 2024-07-03 14:49 UTC by lmlg

# Description

This patchset makes the charm pass all the mon addresses in the relation databag instead of only the local one. This is meant to workaround this issue: https://bugs.launchpad.net/snap-openstack/+bug/2066167

## Type of change

- New feature (non-breaking change which adds functionality)

## Contributor's Checklist

Please check that you have:

- [X] self-reviewed the code in this PR.

2024-07-04 05:45 UTC, hemanthnakkina approved these changes

2024-07-04 05:45 UTC, hemanthnakkina commented
@lmlg LGTM, will await changes in client side - https://github.com/openstack/charm-ops-interface-ceph-client/blob/master/interface_ceph_client/ceph_client.py#L100-L128

2024-07-04 06:58 UTC, hemanthnakkina requested changes
Can `ceph-public-addresses` be added to application databag instead of unit databag

2024-07-04 17:36 UTC, lmlg commented
> Can `ceph-public-addresses` be added to application databag instead of unit databag

I can do that, but I'm wondering what would be the benefit of doing so?

2024-07-05 03:16 UTC, hemanthnakkina commented
> > Can `ceph-public-addresses` be added to application databag instead of unit databag
> 
> I can do that, but I'm wondering what would be the benefit of doing so?

The usual approach is any application related data should be updated in application databag (which can be done by only leader unit) and if each unit has specific info to update then it should go to unit databag. Since the MON IPs are not specific to unit, `ceph-public-addresses` should go to application databag. 
Imagine a hypothetical situation where the leader got changed and there is an update of mon's and the old leader went into paused state with no relation data updates. Then the client side will see 2 different ceph-public-addresses from microceph units if `ceph-public-addresses` is in unit databag.

Also may be we should rename `ceph-public-addresses` to `ceph-mon-public-addresses` to be more specific.
(In future we might add public addresses for other services)

2024-07-12 11:14 UTC, UtkarshBhatthere commented
+1 on using `ceph-mon-public-addresses`

2024-07-22 02:56 UTC, hemanthnakkina commented
@lmlg Can you rebase the PR

2024-07-31 08:56 UTC, UtkarshBhatthere commented
Note: Merging this PR irrespective of the CephMDS failure: Tracking at #103

2024-07-31 08:56 UTC, UtkarshBhatthere approved these changes
LGTM

2024-07-31 08:58 UTC, merged